In [76]:
import pandas as pd
import numpy as np

In [77]:
customers_df = pd.read_excel('../Datasets/customer_data.xlsx')
customers_df.head(5)

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [78]:
missing_values = customers_df.isnull().sum()
print('missing values in each column:\n', missing_values)

missing values in each column:
 CustomerID                  0
Gender                      0
Age                         0
Income                      5
City                        3
Region                      0
Frequency_of_Purchases      0
Average_Purchase_Amount     0
Customer_Lifespan_Months    0
Purchase_Channel            0
Date_of_Purchase            0
Churn_Status                0
dtype: int64

In [79]:
from sklearn.impute import SimpleImputer

In [80]:
imputer = SimpleImputer(strategy='median')   
imputer_2 = SimpleImputer(strategy='most_frequent')

customers_df['Income'] = imputer.fit_transform(customers_df[['Income']])[:,0]
customers_df['City'] = imputer_2.fit_transform(customers_df[['City']])[:,0]

In [81]:
missing_values = customers_df.isnull().sum()
print('missing values in each column:\n', missing_values)

missing values in each column:
 CustomerID                  0
Gender                      0
Age                         0
Income                      0
City                        0
Region                      0
Frequency_of_Purchases      0
Average_Purchase_Amount     0
Customer_Lifespan_Months    0
Purchase_Channel            0
Date_of_Purchase            0
Churn_Status                0
dtype: int64

In [82]:
customers_df['Customer_Lifespan_Months'].unique()

array([3, 4, 1, 2, 5, 'XXXX'], dtype=object)

In [83]:
customers_df = customers_df[customers_df['Customer_Lifespan_Months'] != 'XXXX']
customers_df['Customer_Lifespan_Months'].unique()

array([3, 4, 1, 2, 5], dtype=object)

In [84]:
customers_df['Customer_Lifespan_Months'] = customers_df['Customer_Lifespan_Months'].astype(int)
customers_df['Date_of_Purchase'] = customers_df['Date_of_Purchase'].astype('datetime64[ns]')
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 0 to 80
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                80 non-null     object
 1   Gender                    80 non-null     object
 2   Age                       80 non-null     int64
 3   Income                    80 non-null     float64
 4   City                      80 non-null     object
 5   Region                    80 non-null     object
 6   Frequency_of_Purchases    80 non-null     int64
 7   Average_Purchase_Amount   80 non-null     float64
 8   Customer_Lifespan_Months  80 non-null     int64
 9   Purchase_Channel          80 non-null     object
 10  Date_of_Purchase          80 non-null     datetime64[ns]
 11  Churn_Status              80 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(3), object(6)
memory usage: 8.1+ KB

In [85]:
dup_cus = customers_df.duplicated()
customers_df[dup_cus]

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
80,C021,Female,22,41743.0,Los Angeles,Northeast,4,54.599,1,Online,2023-06-08,No

In [86]:
customers_df.drop_duplicates(inplace=True)
customers_df[dup_cus]

C:\Users\thapa\AppData\Local\Temp\ipykernel_13960\1656588182.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  customers_df[dup_cus]

Empty DataFrame
Columns: [CustomerID, Gender, Age, Income, City, Region, Frequency_of_Purchases, Average_Purchase_Amount, Customer_Lifespan_Months, Purchase_Channel, Date_of_Purchase, Churn_Status]
Index: []

In [87]:
sorted_df = customers_df.sort_values(by='Income', ascending=False)
sorted_df.head(5)

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
55,C056,Female,29,107662.0,Houston,Northeast,3,47.877,1,In-store,2022-02-11,No
22,C023,Female,41,105186.0,Los Angeles,Midwest,14,137.697,4,Online,2023-07-15,Yes
70,C071,Female,36,103264.0,Los Angeles,Northeast,11,117.394,3,Online,2023-12-22,Yes
32,C033,Female,31,98590.0,Houston,West,7,76.114,2,Online,2023-06-30,No
52,C053,Female,45,90860.0,Houston,Northeast,10,105.287,3,In-store,2023-12-29,Yes

In [88]:
customers_df.loc[0:5, 'CustomerID':'Region']

  CustomerID  Gender  Age   Income      City     Region
0       C001    Male   49  72504.0   Chicago  Northeast
1       C002  Female   38  40881.0  New York       West
2       C003    Male   17  63333.0  New York  Northeast
3       C004    Male   34  58030.0   Chicago    Midwest
4       C005    Male   30  78889.0   Houston    Midwest
5       C006    Male   52  76470.0   Chicago    Midwest

In [89]:
customers_df.iloc[0:5, 0:5]

  CustomerID  Gender  Age   Income      City
0       C001    Male   49  72504.0   Chicago
1       C002  Female   38  40881.0  New York
2       C003    Male   17  63333.0  New York
3       C004    Male   34  58030.0   Chicago
4       C005    Male   30  78889.0   Houston

In [90]:
male_customers = customers_df[customers_df['Gender'] == 'Male']
print(male_customers.head(5))

  CustomerID Gender  Age   Income      City     Region  \
0       C001   Male   49  72504.0   Chicago  Northeast
2       C003   Male   17  63333.0  New York  Northeast
3       C004   Male   34  58030.0   Chicago    Midwest
4       C005   Male   30  78889.0   Houston    Midwest
5       C006   Male   52  76470.0   Chicago    Midwest

   Frequency_of_Purchases  Average_Purchase_Amount  Customer_Lifespan_Months  \
0                      10                   98.241                         3
2                       1                   41.252                         1
3                       6                   67.329                         1
4                       3                   52.763                         1
5                      11                  117.012                         3

  Purchase_Channel Date_of_Purchase Churn_Status
0           Online       2022-03-05          Yes
2           Online       2023-01-30           No
3         In-store       2023-06-01           No
4           Online       2022-09-23           No
5           Online       2022-11-30          Yes

In [91]:
Freq_male = male_customers[male_customers['Frequency_of_Purchases'] > 5 ]
print(Freq_male.head(5))

  CustomerID Gender  Age   Income         City     Region  \
0       C001   Male   49  72504.0      Chicago  Northeast
3       C004   Male   34  58030.0      Chicago    Midwest
5       C006   Male   52  76470.0      Chicago    Midwest
7       C008   Male   38  38401.0      Houston       West
8       C009   Male   44  73105.0  Los Angeles  Northeast

   Frequency_of_Purchases  Average_Purchase_Amount  Customer_Lifespan_Months  \
0                      10                   98.241                         3
3                       6                   67.329                         1
5                      11                  117.012                         3
7                       6                   70.730                         2
8                      12                  124.887                         3

  Purchase_Channel Date_of_Purchase Churn_Status
0           Online       2022-03-05          Yes
3         In-store       2023-06-01           No
5           Online       2022-11-30          Yes
7           Online       2022-05-24           No
8           Online       2022-09-02          Yes

In [92]:
performance_df = pd.read_excel('../Datasets/performance_data.xlsx')
performance_df.head(5)

  CustomerID  Recency  Frequency_Score  Monetary_Score
0       C001        3                2               2
1       C002        3                3               3
2       C003        4                4               4
3       C004        2                2               2
4       C005        1                1               1

In [93]:
joined_df = customers_df.merge(performance_df, on='CustomerID', how='inner')
joined_df.head(5)

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,Recency,Frequency_Score,Monetary_Score
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes,3,2,2
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes,3,3,3
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No,4,4,4
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No,2,2,2
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No,1,1,1

In [94]:
additional_data_df = pd.read_excel('../Datasets/additional_data.xlsx')
additional_data_df.head(5)

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,CustomerID.1,Recency,Frequency_Score,Monetary_Score
0,C081,Male,37,50728,Chicago,West,11,75.757,2,In-store,2023-09-10,Yes,C081,2,2,1
1,C082,Female,48,69629,Los Angeles,Midwest,9,78.433,4,In-store,2023-07-15,No,C082,3,4,4
2,C083,Male,28,29184,Chicago,Northeast,7,82.794,3,Online,2023-08-25,Yes,C083,3,1,2
3,C084,Female,33,61265,Los Angeles,West,15,88.490,2,Online,2022-10-22,Yes,C084,4,1,3
4,C085,Female,30,63130,Houston,Midwest,13,108.749,3,Online,2023-04-01,Yes,C085,4,4,1

In [95]:
final_df = pd.concat([joined_df.reset_index(drop=True), additional_data_df.reset_index(drop=True)])
final_df.head(5)

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,Recency,Frequency_Score,Monetary_Score,CustomerID.1
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05 00:00:00,Yes,3,2,2,NaN
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08 00:00:00,Yes,3,3,3,NaN
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30 00:00:00,No,4,4,4,NaN
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01 00:00:00,No,2,2,2,NaN
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23 00:00:00,No,1,1,1,NaN

In [96]:
final_df = round(final_df.drop(columns=['CustomerID.1'], axis=1), 2)
final_df.head(5)

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,Recency,Frequency_Score,Monetary_Score
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.24,3,Online,2022-03-05 00:00:00,Yes,3,2,2
1,C002,Female,38,40881.0,New York,West,15,157.64,4,In-store,2023-07-08 00:00:00,Yes,3,3,3
2,C003,Male,17,63333.0,New York,Northeast,1,41.25,1,Online,2023-01-30 00:00:00,No,4,4,4
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.33,1,In-store,2023-06-01 00:00:00,No,2,2,2
4,C005,Male,30,78889.0,Houston,Midwest,3,52.76,1,Online,2022-09-23 00:00:00,No,1,1,1

In [97]:
freq_purchase_channel = final_df['Purchase_Channel'].value_counts()
freq_purchase_channel

Purchase_Channel
Online      65
In-store    34
Name: count, dtype: int64

In [98]:
Perc_purchase_channel = freq_purchase_channel / len(final_df) * 100
Perc_purchase_channel

Purchase_Channel
Online      65.656566
In-store    34.343434
Name: count, dtype: float64

In [99]:
city_purchase_amount = final_df.groupby('City')['Average_Purchase_Amount'].median()
city_purchase_amount

City
Chicago        102.190
Houston         87.660
Los Angeles    100.725
New York        95.470
Name: Average_Purchase_Amount, dtype: float64

In [115]:
pivot_table = final_df.pivot_table(index='Churn_Status', values=['Recency', 'Frequency_Score', 'Monetary_Score'], aggfunc={'Recency': 'median', 'Frequency_Score': 'mean', 'Monetary_Score': 'mean','Churn_Status': 'count'})

In [117]:
pivot_table = pivot_table.rename(columns={'Churn_Status':'Freq_Churn', 'Recency':'Median_Recency', 'Frequency_Score':'Mean_Frequency_Score', 'Monetary_Score':'Mean_Monetary_Score','Freq_Churn':'Count_Churn_Status'})
pivot_table

,Count_Churn_Status,Mean_Frequency_Score,Mean_Monetary_Score,Median_Recency
Churn_Status,,,,
No,43,2.744186,2.558140,3.0
Yes,56,2.482143,2.482143,3.0

In [120]:
cross_tab = pd.crosstab(final_df['City'], final_df['Purchase_Channel'])
cross_tab

Purchase_Channel  In-store  Online
City
Chicago                  8      17
Houston                 11      21
Los Angeles              9      15
New York                 6      12